import assert from 'node:assert/strict';
import { initialGrid, gridReducer, gridPath } from '../htdocs/grid_state.js';
import { OperationState } from '../htdocs/operation_state.js';
import { encodePattern } from '../htdocs/pattern_encoding.js';

let state = initialGrid();
const paint = (row, col, color) => { state = gridReducer(state, { type: 'paint', row, col, color }); };
paint(0, 0, 'RED');
paint(0, 1, 'BLUE');
assert.equal(gridPath(state.cells), 'REDA0BLUEB0');
paint(0, 0, 'GREEN');
assert.equal(gridPath(state.cells), 'BLUEB0GREENA0');
state = gridReducer(state, { type: 'undo' });
assert.equal(gridPath(state.cells), 'REDA0BLUEB0', 'undo restores both color and order');
paint(0, 0, null);
assert.equal(gridPath(state.cells), 'BLUEB0');
state = gridReducer(state, { type: 'undo' });
assert.equal(gridPath(state.cells), 'REDA0BLUEB0', 'undo restores cleared cell');
state = gridReducer(state, { type: 'undo' });
state = gridReducer(state, { type: 'undo' });
assert.equal(gridPath(state.cells), '');
assert.deepEqual(gridReducer(state, { type: 'undo' }), state);
paint(1, 1, 'BLACK');
assert.equal(gridPath(gridReducer(state, { type: 'reset' }).cells), '');

assert.equal(encodePattern([{ dir: 'RU' }]), '1');
assert.equal(encodePattern([{ dir: 'R' }, { dir: 'U' }]), '02');
assert.equal(encodePattern(['R', 'RU', 'U', 'LU', 'L', 'LD', 'D', 'RD'].map(dir => ({ dir }))), '01234567');

const tasks = new OperationState();
assert.equal(tasks.begin('encrypt'), null, 'cannot submit before Worker initialization');
tasks.ready = true;
const first = tasks.begin('encrypt');
assert.equal(tasks.begin('decrypt', 'manager'), null, 'manager cannot overlap active job');
assert.equal(tasks.accepts({ action: 'encrypt', requestId: first.requestId + 1 }), false);
assert.equal(tasks.accepts({ action: 'decrypt', requestId: first.requestId }), false);
assert.equal(tasks.accepts(first), true);
tasks.finish();
const second = tasks.begin('decrypt', 'manager');
assert.equal(tasks.accepts(first), false, 'late first result cannot complete second job');
assert.equal(tasks.finish().origin, 'manager');
tasks.saving = true;
assert.equal(tasks.begin('encrypt'), null, 'cannot overwrite output while saving');
tasks.saving = false;
assert.ok(tasks.begin('encrypt'));
console.log('Business state regression passed: undo/order, direction encoding, initialization, overlap, stale replies, save lock.');
