import assert from 'node:assert/strict';
import { VaultClient } from '../htdocs/vault_client.js';
import { PasswordService } from '../htdocs/password_service.js';
const workers=[];
const client=new VaultClient(()=>{
    const worker={postMessage(message){this.message=message},terminate(){this.terminated=true}};
    workers.push(worker);return worker;
});
const first=client.request('vault_unlock');
const old=workers[0], oldReply=old.onmessage;
const rejection=assert.rejects(first,/locked/);
client.lock();await rejection;
assert.equal(old.terminated,true);
const next=client.request('vault_create');
const current=workers[1];
oldReply({data:{requestId:old.message.requestId,status:'success',result:'stale'}});
old.onerror();
assert.equal(client.pending.size,1,'a reply from a terminated worker must not restore the session');
current.onmessage({data:{requestId:current.message.requestId,status:'success',result:'new'}});
assert.equal(await next,'new');client.lock();
globalThis.localStorage={getItem:()=>''};
const service=new PasswordService();
let calls=0;
globalThis.fetch=async()=>{calls++;return new Response('{"error":"changed"}',{status:409})};
const vault={id:1,type:'vault',vaultId:crypto.randomUUID(),revision:1,name:'Test',description:'',password:'WVK1.example',children:[]};
await assert.rejects(service.saveVault(vault), error=>error.status===409 && !error.message.includes('may have reached'));
assert.equal(calls,1,'conflicts must not be retried');
await assert.rejects(service.saveVault({...vault,children:[{id:crypto.randomUUID(),name:'leak',description:'',password:'WVI1.test'}]}));
assert.equal(calls,1,'plaintext metadata must not reach the server');
console.log('Vault client passed: pending cancellation, terminated-worker isolation, conflict status and metadata validation.');
